---
title: "Math Modeling Final Project"
author: "Jason Whitelaw"
date: "4/13/2022"
output: html_document
---

```{r}
library(tidyverse)
library(ggthemes)
theme_set(theme_minimal())
```

```{r}
basketball <- read_csv("jason_wp.csv")
```

```{r}
f <- function(x, y, z) {
}
```

```{r}
basketball_clean <- basketball %>%
  mutate(time = (q-1)*12 + (11-min) + (1-(sec/60))) %>%
  group_by(gid) %>%
  mutate(temp_and1 = grepl("Free Throw 1 of 1", d) & !grepl("MISS", d) & grepl("S.FOUL", lag(d))) %>%
  mutate(and1 = case_when(temp_and1 == TRUE & gst1 == "A" ~ 1, temp_and1 == TRUE & gst1 == "H" ~ 2, TRUE ~ 0))
basketball_clean
```


```{r}
basketball_clean %>%
  filter(gid == "0021800001") %>%
  ggplot() +
  geom_line(aes(x = time, y = wpl)) +
  geom_vline(aes(xintercept = 8.2166667), color = "green") + 
  geom_vline(aes(xintercept = 30.63333), color = "green") + 
  geom_vline(aes(xintercept = 42.0166667), color = "red") + 
  ylim(0,1) +
  xlim(0,48) +
  labs(title = "Win Probability for Celtics vs. 76ers")
```

```{r}
f <- function(x) {
  1/(1+exp(5*x-7))
}

ggplot() +
  geom_point(aes(x = 0, y = 1)) +
  geom_point(aes(x = 28.6/60, y = 1)) +
  geom_point(aes(x = 57.2/60, y = .75)) +
  geom_point(aes(x = 85.8/60, y = .5)) +
  geom_point(aes(x = 114.4/60, y = .25)) +
  geom_point(aes(x = 143/60, y = 0)) +
  geom_function(fun = f)+
  xlim(0,12) +
  ylim(0,1)
```

$$
w = wpl + \prod (1+\frac{1}{1+e^{5t-7}}) - 1
$$










